### ISSUE TITLE
Incompatible with recent Node.js version (12.16.0)

### ISSUE THREAD

**Issue by moritz-a** [swisspush/apikana#109]
Throws error after trying to run apikana 0.7.6 with Node 12.16.0 (includes npm 6.13.4) on Windows 10 x64

**Reproduce:**

1. Install Node.js LTS 12.16.0 (includes npm 6.13.4)
2. Install apikana 0.7.6 with npm
3. Create new project 

> apikana init

4. Try to run 

> npm  start

**Workaround:**
Downgrade Node.js i.e. Node.js 10.15.1 / npm 6.4.1

**Stacktrace:**
```
morit@DESKTOP-LLH1ME3 MINGW64 ~/dev/apikTest/spielplatz-stream-api
$ npm start

> @moritz/spielplatz-stream-api@0.1.0-rc.1 start C:\Users\morit\dev\apikTest\spielplatz-stream-api
> apikana start src dist

[10:04:07]                                        AAPIKA
[10:04:07]      PIKANAAPIKANA    ANA            NAA    NA
[10:04:07]                NAA    NAA            AAP    AA
[10:04:07]          AP    AAP    AAP    AAPI      IKANAA
[10:04:07]          PI   AAP     APIKANAAP
[10:04:07]          IK  AAP      PIKAN
[10:04:07]          KANAAP       IKA
[10:04:07]         KAN           KAN
[10:04:07]         ANA           ANA
[10:04:07]        ANA            NAA
[10:04:07]      KANA              APIKANAAPI
[10:04:07]     KAN                 IKANAAPIKA        apikana 0.7.6
[10:04:07]
[10:04:07] Source:  src
Loading defaults... found 0.0.0
(node:26816) UnhandledPromiseRejectionWarning: ReferenceError: primordials is not defined
    at fs.js:35:5
    at req_ (C:\Users\morit\dev\apikTest\spielplatz-stream-api\node_modules\apikana\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\morit\dev\apikTest\spielplatz-stream-api\node_modules\apikana\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\morit\dev\apikTest\spielplatz-stream-api\node_modules\apikana\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
(node:26816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:26816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by lbovet** [comment]
Will not yet be solved. In 0.7.7, an explicit check will be done with a clear error message.
